### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by mattn**
Why lcl?

### CODE REVIEW

**Comment by 1xch** [comment]
I had thought I fixed this before sending out and announcing. I have a copy installed locally at 'lcl'. I changed it for the master and tagged, but I'm guessing that go get install will install the develop version because thats set as the primary branch.

**Comment by mattn** [comment]
Thank you. BTW, this sill have runtime error.

```
panic: path must begin with '/'
```

Because engine.router.Handle check the leading slash.

**Comment by 1xch** [comment]
Yes that would be from the router & here I'm guessing:

https://github.com/thrisp/engine/blob/develop/group.go#L48

Make sure all RouterGroup prefixes start with a '/' would be a starting suggestion.

**Comment by mattn** [comment]
On windows it's shoule be `\`

**Comment by 1xch** [comment]
@mattn 
hmmm, ok. I don't know or use windows, so I can only guess what might happen in that environment. I'm glad Go is that flexible in compilation without a lot of extra work. Can you post exactly how you needed to use the "\"?

**Pull request merged**
